### ISSUE TITLE
[BUG] Error on Mac restart 

### ISSUE THREAD

**Issue by cotfas** [SamSchott/maestral#137]
Latest stable version 1.0.0
Catalina 10.15.4

<img width="430" alt="err" src="https://user-images.githubusercontent.com/3340367/81354006-316dcc80-90d3-11ea-93da-3f7878074247.png">

On mac restart I get this error.. It is the second time (second time restarted the mac) and I noticed this error. Just to mention, my wifi is set on the auto connect as disabled, so everytime I restart the mac I do manually connect to wifi, the error might be related to this scenario, and after I manually connect to wifi I open the Maestral app and it works.

BTW: Very nice that you launched the stable version. :)

**Comment by SamSchott** [comment]
Strange, I was initially able reproduce this myself. But after redirecting output from the startup process to the log files (to figure out what was going on), the problem vanished. And now, whatever I try, I cannot recreate the problem.

Could you try the following? Startup on login is handled by a file `~/Library/LaunchAgents/com.samschott.maestral.maestral.plist` with the following content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.samschott.maestral.maestral</string>
	<key>ProcessType</key>
	<string>Interactive</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Applications/Maestral.app/Contents/MacOS/main</string>
		<string>gui</string>
		<string>-c</string>
		<string>maestral</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

Could you add the the following keys to it

```xml
<key>StandardOutPath</key>
<string>/Users/USERNAME/Desktop/maestral_out.log</string>
<key>StandardErrorPath</key>
<string>/Users/USERNAME/Desktop/maestral_err.log</string>
```

where USERNAME should be replaced by your user username and check the output printed to the log files on restart? This should be able to log any errors during startup before Maestral has set up its own logging facilities.

**Comment by cotfas** [comment]
I have tried what you suggested:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.samschott.maestral.maestral</string>
	<key>ProcessType</key>
	<string>Interactive</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Applications/Maestral.app/Contents/MacOS/main -c 'maestral'</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardOutPath</key>
	<string>/Users/work/Desktop/maestral_out.log</string>
	<key>StandardErrorPath</key>
	<string>/Users/work/Desktop/maestral_err.log</string>
</dict>
</plist>

On first restart, I got the same dialog popup error, and both files are 0kb, I have restarted, the same both files 0kb, but this time I got no dialog error, and I found the app in the statusbar running. Weird.

I will try to chmod both files and see the result on restart, and then back to original for plist to see if the issue still reproduce.

BTW: Maybe is related, my wifi is set to enable but will not connect to any network on restart, when I restart the mac, I have to manually connect to my wifi network, maybe this is related.

**Comment by cotfas** [comment]
RE:

chmod 755 maestral* did not helped, 0kb on both files, and no error dialog.

I`ve changed StandardOutPath, StandardOutPath to other path and I will leave it there as it seems with those two settings the app starts at mac restart.

**Comment by SamSchott** [comment]
Thanks for checking, it does seem that the issue reproducibly vanishes after the first successful launch. The main change which could cause startup problem: the GUI now launches a separate daemon process instead of running the daemon "internally". This may be blocked somehow by macOS if the app or the launchd file is not trusted. It is possible that just manually modifying the launchd file is enough and setting the paths makes no difference. But its difficult to investigate without being able to reproduce the error.

> BTW: Maybe is related, my wifi is set to enable but will not connect to any network on restart, when I restart the mac, I have to manually connect to my wifi network, maybe this is related.

This shouldn't cause any issues. The daemon will start regardless of available internet connections.

**Comment by SamSchott** [comment]
This should hopefully fixed in the latest release where the daemon is spawned instead of forked. There seems to be a long standing issue with forking processes that access macOS system frameworks.

**Comment by cotfas** [comment]
Still having some issues, I use the 1.0.3 version, mac 10.15.5, and use the CLI version, on the System>users> the maestral is not there for login, on the GUI the "start maestral at login" is disabled, and I have the maestral cli running, when performing a mac restart or user logout/login, the GUI starts-up and the cli is not running, how I can make it to autostart the cli and the gui to be disabled at login? Maybe a setup in the gui to thick on when to start the cli at login will be nice.

**Comment by SamSchott** [comment]
> Maybe a setup in the gui to thick on when to start the cli at login will be nice.

I will consider that. For now, the CLI command `maestral autostart -Y` should only trigger the daemon to start on login while the GUI checkbox starts the GUI. It is ok to have both activated at the same time, the GUI will attach itself to a running daemon if it finds one. As usual, you can check with `maestral status` if it’s actually running.

> on the System>users> the maestral is not there for login

I’m not sure why those entries are missing but I have encountered the same issue. I suspect it’s because the way that the login items are registered does not quite conform to Apple’s guidelines. But doing it the official way is a bit complicated and involves writing a separate helper program which launches the actual daemon or GUI.

There should however be appropriate items at `~/Library/LaunchAgents` and the app should start properly on login, even if the entries are not shown in the system preferences.

**Comment by cotfas** [comment]
Hello

The issue still persists, maestral 1.0.3, enabled only CLI, and disabled on GUI autostart, and from System->Users the same removed it from there, and when I restart the mac 10.15.5, it starts the GUI instead of CLI, and I have to close the GUI and go to terminal and do 'maestral start' :(

**Comment by SamSchott** [comment]
Yes, I can reproduce this. The problem is an incorrect executable path in the startup item.

If you look at the file `~/Library/LaunchAgents/com.samschott.maestral-daemon.maestral.plist`, its content will be:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.samschott.maestral-daemon.maestral</string>
	<key>ProcessType</key>
	<string>Interactive</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Applications/Maestral.app/Contents/MacOS/main</string>
		<string>start</string>
		<string>-f</string>
		<string>-c</string>
		<string>maestral</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

However, the first "program argument" should be the path of the command line tool `/usr/local/bin/maestral` instead of the app bundle. You can correct this manually for now, until I can provide an update. Just be aware that toggling the autostart option will recreate an incorrect startup item.

**Comment by SamSchott** [comment]
Ok, this should be finally fixed now in v1.1.0. This release also addresses an issue when the GUI tries to start syncing at the same time as the CLI, which would result in multiple watchdog threads.

You'll need to recreate both GUI and CLI startup items by turning "start on login" off and on again.

Sorry about all the trouble!

**Comment by cotfas** [comment]
Does not work, after I updated to 1.1.0, I went to gui and ticked the auto login and unticked, and then cli maestral start, and also maestral autostart -Y and it returned success, today, I had to do a mac restart and I noticed that the files were not syncing, terminal:

192-168-0-103:~ work$ maestral status
Maestral daemon is not running.
192-168-0-103:~ work$

**Comment by SamSchott** [comment]
Damn. Could you paste the content of `~/Library/LaunchAgents/com.samschott.maestral-daemon.maestral.plist`?

**Comment by cotfas** [comment]
Yes,

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.samschott.maestral-daemon.maestral</string>
	<key>ProcessType</key>
	<string>Interactive</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Applications/Maestral.app/Contents/MacOS/main</string>
		<string>start</string>
		<string>-f</string>
		<string>-c</string>
		<string>maestral</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>

Last modified date on disk: 

Wednesday, May 13, 2020 7:57:52 PM

**Comment by cotfas** [comment]
I don`t remember to see the gui launched after the restart (not 100% sure, normally on restart I were closing the gui from the statusbar and then went to terminal).

**Comment by SamSchott** [comment]
That entry looks old and wrong. Can you delete it (manually or with `maestral autostrat -N`) and then recreate it?

**Comment by cotfas** [comment]
Did not saw your last message. I did another mac restart ( bluescreen:| ), after restarted the gui did not launched and cli

192-168-0-103:~ work$ maestral status
Maestral daemon is not running.
192-168-0-103:~ work$

**Comment by cotfas** [comment]
Deleted the plist

Ran:

192-168-0-103:~ work$ maestral autostart -Y
Enabled start on login.
192-168-0-103:~ work$ maestral start
Starting Maestral...        [OK]
192-168-0-103:~ work$


File recreated

	<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
	<plist version="1.0">
	<dict>
	    <key>Label</key>
	    <string>com.samschott.maestral-daemon.maestral</string>
	    <key>ProcessType</key>
	    <string>Interactive</string>
	    <key>ProgramArguments</key>
	    <array>
			<string>/usr/local/bin/maestral</string>
			<string>start</string>
			<string>-f</string>
			<string>-c</string>
			<string>maestral</string>
	    </array>
	    <key>RunAtLoad</key>
	    <true/>
	</dict>
	</plist>

Will ping you on next restart if anything ocurs. TNX

**Comment by SamSchott** [comment]
That looks much better!

The GUI should hopefully also work after deleting and recreating its plist `~/Library/LaunchAgents/com.samschott.maestral.maestral.plist` by turning the “start on login” checkbox off and on again.

Ping me if it’s still causing issues, but I thought I had thoroughly tested the changes this time.
