### ISSUE TITLE
[BUG] First run of maestral shows unexpected inotify errors

### ISSUE THREAD

**Issue by Roy-Orbison** [SamSchott/maestral#241]
**Describe the bug**
It appears as though Maestral is adding unnecessary watches outside of the dropbox directory. The following messages were visible in the console:

> ```text
> inotify_add_watch(/lost+found) failed: (Permission denied)
> inotify_add_watch(/mnt/bigdrive/lost+found) failed: (Permission denied)
> inotify_add_watch(/root) failed: (Permission denied)
> ```

**To Reproduce**
1. Install Maestral from a shell
2. Run `maestral gui` from the same shell
3. Go through the setup process.  
    Unsure if relevant but I renamed an existing dropbox dir in order to merge its contents, first removing the `.dropbox*` files from its root.
4. Wait for initial sync
4. View the output in the shell

**Expected behaviour**
No error messages, or at least errors only on dirs that are at or below the dropbox dir.

**System (please complete the following information):**
 - Maestral version: GUI v1.2.3, daemon v1.2.2
 - OS: Ubuntu
 - Desktop environment: KDE
 - Qt version: 5.14.2

**Comment by SamSchott** [comment]
Hrm, it should not care at all about those folders (or try to watch them). Do those messages reoccur between startups? It looks like at some point the daemon is attempting to monitor your entire drive, which is a really bad idea for multiple reasons.

**Comment by Roy-Orbison** [comment]
That's what I feared, but I haven't seen those same errors in console again after manual starts.

It sometimes crashes though when I click _Selective sync_ in the prefs window. I did notice that you had put in a fix for this in 1.2.2:
> * Fixes an issue with the Qt GUI crashing when opening the selective sync dialog if one of the folders contains a large number (> 2k) of immediate children.

but I already have that version. I think it only crashes if I open that when it's mid-sync (icon is cyclic arrows).

**Comment by Roy-Orbison** [comment]
Scratch that, it still just crashes even when not syncing but I guess that's a new issue.

**Comment by SamSchott** [comment]
Yeah, there have been some lingering issues with that dialog in the Qt GUI. I hope to have those fully fixed in the next release. However, I could not reproduce a crash with v1.2.2 -- only missing folder content in case of > 10 folders.

**Comment by Roy-Orbison** [comment]
I think this is still happening in some way because every boot I get a toast notification from Maestral saying:

>#### Examining (Failed)
>/tmp/mozilla_roy0

**Comment by Roy-Orbison** [comment]
@SamSchott Do you have any advice about debugging this? I'm now seeing warnings from Maestral that my inotify watch limit is too low, and it isn't (it's set at > 500k and the number of inodes in the dropbox folder is < 120k).

**Comment by SamSchott** [comment]
@Roy-Orbison, apologies for the lack of progress on this. This is partially because I cannot reproduce the original issue: In all my attempts, the sync daemon only ever starts inotify watches for folders inside the Dropbox directory. My only suggested right now is to update to the latest version if you haven't done so already and check if the problem persists.

Regarding reaching the inotify limit, there are possibly other applications that are using inotify as well. You can get the number of files being watched by all processes with:
```
lsof | grep inotify | wc -l
```
To see all processes using inotify, ordered by their number of instances:
```
for foo in /proc/*/fd/*; do readlink -f $foo; done | grep inotify | sort | uniq -c | sort -nr
```
This will give output looking like:
```
      4 /proc/9370/fd/anon_inode:inotify
      2 /proc/2942/fd/anon_inode:inotify
      1 /proc/2570/fd/anon_inode:inotify
      1 /proc/2524/fd/anon_inode:inotify
```
where the first number is the number of inotify instances and the second number is the PID.

You can find a good writeup about this at https://transang.me/enospc-inotify-in-ubuntu/.

**Comment by SamSchott** [comment]
I would certainly hope that it has stopped trying!

**Comment by SamSchott** [comment]
The recent release has seen some cleanup to state management when linking or unlinking, possibly solving any issues where a watch may be started when we don't have a local Dropbox folder set up yet. I suspect that this could have been the cause for attempting to watch the root directory.
