### ISSUE TITLE
Regression? `maestral activity` on Mac crashes immediately

### ISSUE THREAD

**Issue by tjluoma** [samschott/maestral#533]
**Describe the bug**

typing `maestral activity` into a terminal window brings up a crash dialog:

<img width="744" alt="maestral activity crash" src="https://user-images.githubusercontent.com/26965/143726763-d3d9ae96-494e-4fca-9cc4-ad80a4d2ff1e.png">

**To Reproduce**
type `maestral activity` into terminal window

**Expected behaviour**
activity will be shown

**System:**

 - Maestral version: 1.5.2 (45)
 - Python version: Python 3.9.8
 - OS: [e.g. Ubuntu] macOS version 12.0.1 (21A559) on an M1-based MacBook Air

**Additional context**

I just updated `maestral` and I think it was working in the previous version.

Here's the contents of the crash as shown in the terminal:

```
Traceback (most recent call last):
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/runpy.py", line 196, in _run_module_as_main
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/runpy.py", line 86, in _run_code
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 41, in <module>
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 36, in freeze_support_cli
  File "Contents/Resources/app_packages/click/core.py", line 1128, in __call__
  File "Contents/Resources/app_packages/click/core.py", line 1053, in main
  File "Contents/Resources/app_packages/click/core.py", line 1659, in invoke
  File "Contents/Resources/app_packages/click/core.py", line 1395, in invoke
  File "Contents/Resources/app_packages/click/core.py", line 754, in invoke
  File "Contents/Resources/app_packages/maestral/cli.py", line 227, in wrapper
  File "Contents/Resources/app_packages/maestral/cli.py", line 1007, in activity
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/curses/__init__.py", line 13, in <module>
ModuleNotFoundError: No module named '_curses'
```

**Comment by SamSchott** [comment]
Indeed, a regression. It appears that the `curses` package which is used for this command is no longer included in the macOS app bundle. Installing as a Python package still works fine, which is why I did not catch it myself.

**Comment by SamSchott** [comment]
This should be fixed now. I've updated the DMG for release v1.5.2.

**Comment by tjluoma** [comment]
It still happens with this version

```
/Applications/Maestral.app:
	CFBundleShortVersionString: 1.5.2
	CFBundleVersion: 46
```

Which says it is the newest version. 

I still can't use the app because of https://github.com/SamSchott/maestral/issues/491

**Comment by SamSchott** [comment]
Reopening because the issue persists. This should be ideally fixed at https://github.com/beeware/Python-Apple-support/.

**Comment by tjluoma** [comment]
Can you tell me how to install the python package myself so I can workaround this in the meantime? Thanks!

**Comment by SamSchott** [comment]
Sure. Here it goes:

1. Since you are using macOS 12, it *should* already have Python 3.8 pre-installed. You can check by running `python3` in a Terminal, this should open an interactive Python prompt. If it is not installed, macOS will offer to install it for you at this point.
2. Install the Python package by running the following command:
    ```
    pip3 install 'maestral[gui]'
    ```
3. Uninstall the CLI which is included with the app bundle. This ensures that the `maestral` command in the terminal will always launch the Python package.

Once you have the Python package installed, maybe you can also run a few tests which might help to debug #491.

**Comment by tjluoma** [comment]
I ran the command as suggested, and removed the CLI tool from `/Applications/Maestral.app/Contents/MacOS/`

I can now run `maestral activity` without it crashing.

I'd be happy to run any tests possible to help with 491. I've had to install the official Dropbox app, which is terrible and bloated and slow and why am I telling you this? Obviously, you know already!

You can reach me via email at `me` @ `tjluoma` dot `com` if that would be easier than 'chatting' in GitHub issues.

**Comment by frozenpandaman** [comment]
Thanks for the workaround!

**Comment by reagle** [comment]
I'm new to maestral, just installed 1.5.2 on macOS 12.1 21C52 arm64 via homebrew cask, and got this error when trying to run `maestral activity`. Any suggestions?

**Comment by samschott** [comment]
Fixed in the latest release.
